backend:
  name: git-gateway
  branch: develop

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "home"
    label: "Home Page"
    folder: "content/home"
    create: false
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Challenges Section", name: "challenges", widget: "text" }
      - { label: "Solution Section", name: "solution", widget: "text" }
      - { label: "Services", name: "services", widget: "text" }
      - { label: "Expertise", name: "expertise", widget: "text" }
      - { label: "Portfolio", name: "portfolio", widget: "text" }
