backend:
  name: git-gateway
  branch: develop

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "expertise"
    label: "Expertise"
    folder: "src/content/expertise"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
